name: Github Actiosn Demo
on: push
jobs:
  Example-Action-jon:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Ths job's status is ${{job.status}}."
    
    
    
